import Head from 'next/head'
import { useRouter } from 'next/router'
import { useMemo } from 'react'
import { Post } from '@/components/pages/posts/post'

const Page = () => {
  const router = useRouter()

  const postId = useMemo(() => {
    return parseInt(router.query.postId as string, 10)
  }, [router.query.postId])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post postId={postId}/>
    </>
  )
}

export default Page
