import Head from 'next/head'
import { Posts } from '@/components/pages/posts'

const Page = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Posts />
    </>
  )
}

export default Page
